### PR TITLE
Now copying fonts

### PR DESCRIPTION
**Pull request by highlabs**

### CODE REVIEW

**Comment by highlabs** [comment]
I changed this task for copy fonts. I relied on copyIcons taks:
```
return gulp.src([config.sourceDir + 'fonts/**/*'])
.pipe(gulp.dest('build/fonts/'));
```

**Comment by jakemmarsh** [comment]
Was this not functioning correctly before? Was it due to the `gulp.src` not being an array?

**Comment by highlabs** [comment]
Nopes, I added my fonts inside /build, because I thought I had no such task for this.
When I tried to add this task in gulp, I find this bug.

**Comment by jakemmarsh** [comment]
Ah okay, good catch then!

My only request before I merge this: instead of the hardcoded `/build/fonts`, could you do `config.buildDir + 'fonts/'`? I see that the copyIcons task makes this mistake as well, but that can be resolved later.

**Comment by highlabs** [comment]
Oh, sure. My mistake. :O

**Comment by jakemmarsh** [comment]
:+1:

**Pull request merged**
